---
AWSTemplateFormatVersion: "2010-09-09"
Description: Bucket with encryption at rest.

Resources:
  EUBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref EUBucket
  BucketArn:
    Description: The ARN of the bucket
    Value: !GetAtt EUBucket.Arn